_wandb:
    value:
        cli_version: 0.21.0
        e:
            8lrtjvx2exjf5i4a0xrdrwrkvlepyp4n:
                codePath: mnist_inference.py
                codePathLocal: mnist_inference.py
                email: abenillouche07@gmail.com
                executable: /usr/bin/python
                host: dsiaspl03
                os: Linux-5.14.0-570.23.1.el9_6.x86_64-x86_64-with-glibc2.39
                program: /home/workspace/benilla/mnist_model/mnist_inference.py
                python: CPython 3.12.3
                root: /home/workspace/benilla/mnist_model
                startedAt: "2025-07-03T08:10:26.614122Z"
                writerId: 8lrtjvx2exjf5i4a0xrdrwrkvlepyp4n
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
                - 105
            "2":
                - 1
                - 41
                - 105
            "4": 3.12.3
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
